services:
  # Flask Application (SQLite)
  web:
    build: .
    container_name: bsh-complaints-app
    ports:
      - "8080:8080"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY:-your-openai-api-key}
      - SECRET_KEY=${SECRET_KEY:-super-secret-key-for-development}
      - FLASK_ENV=development
      - PORT=8080
      - DB_PATH=/app/data/bsh_complaints.db
    volumes:
      - ./static:/app/static
      - ./templates:/app/templates
      - ./data:/app/data
    restart: unless-stopped